In [4]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [5]:
data = pd.read_excel('data scaling.xlsx')
data

,NIK,Nama,BB Lahir,TB Lahir,Berat,Tinggi,Label Aktual
0,5202080606192554,KEISYA PUTRI,3.1,50,9.0,66.0,GIZI LEBIH
1,5202084301202131,NUR SYUHADA,3.2,48,5.7,55.0,GIZI LEBIH
2,5202081307190004,HAIDAR ALI,2.7,51,8.1,61.0,GIZI LEBIH
3,5202084609190008,AMELIA MUTIARA IBRAHIM,2.9,49,7.3,60.0,GIZI LEBIH
4,5202080812190007,M. SAPIK AZRULLAH,3.0,50,6.3,56.0,GIZI LEBIH
...,...,...,...,...,...,...,...
241,5202080812201000,MUHAMAD GILANG,2.7,48,7.8,77.0,GIZI KURANG
242,5202082905190133,SUKMADANI PRAYASA,3.1,51,11.2,93.5,GIZI KURANG
243,5202804711212960,ZAFIRA NOVIANI,2.6,49,6.9,72.3,GIZI KURANG
244,5202083103196754,M. ZIKRI,3.0,49,11.7,94.0,GIZI KURANG
245,5202806503180011,ERLIN MARLINA,3.0,48,12.4,99.6,GIZI KURANG

In [14]:
columns_to_scale = ['BB Lahir', 'TB Lahir', 'Berat', 'Tinggi']

In [15]:
scaler = MinMaxScaler()

In [16]:
data[columns_to_scale] = scaler.fit_transform(data[columns_to_scale])

In [18]:
data.to_excel('data true final.xlsx', index=False)