In [14]:
import pandas as pd
import numpy as np

In [15]:
data_c = pd.read_excel('data clean.xlsx')
data_c

,NIK,Nama,JK,Tgl Lahir,BB Lahir,TB Lahir,Nama Ortu,Prov,Kab/Kota,Kec,...,Posyandu,RT,RW,Alamat,Usia Saat Ukur,Tanggal Pengukuran,Berat,Tinggi,Jml Vit A,Label Aktual
0,5202080606192554,KEISYA PUTRI,P,2019-06-06,3.1,50,SRI SEKAR NOVIA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,CINTA DAMAI,1,3,KARANG JANGKONG,0 TAHUN - 8 BULAN - 17 HARI,2020-02-22,9.0,66.0,1,GIZI LEBIH
1,5202084301202131,NUR SYUHADA,P,2020-01-03,3.2,48,NURUL FATIHA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,CINTA DAMAI,1,3,KARANG JANGKONG,0 TAHUN - 1 BULAN - 19 HARI,2020-02-22,5.7,55.0,1,GIZI LEBIH
2,5202081307190004,HAIDAR ALI,L,2019-07-13,2.7,51,KASIRUN,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,0 TAHUN - 7 BULAN - 7 HARI,2020-02-19,8.1,61.0,1,GIZI LEBIH
3,5202084609190008,AMELIA MUTIARA IBRAHIM,P,2019-09-06,2.9,49,IBRAHIM,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,0 TAHUN - 5 BULAN - 13 HARI,2020-02-19,7.3,60.0,1,GIZI LEBIH
4,5202080812190007,M. SAPIK AZRULLAH,L,2019-12-08,3.0,50,MUSTARA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,0 TAHUN - 2 BULAN - 12 HARI,2020-02-19,6.3,56.0,1,GIZI LEBIH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,5202080812201000,MUHAMAD GILANG,L,2020-12-08,2.7,48,YANA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,1,3,MONTONG ARA,2 TAHUN - 2 BULAN - 20 HARI,2023-02-28,7.8,77.0,1,GIZI KURANG
242,5202082905190133,SUKMADANI PRAYASA,L,2019-05-29,3.1,51,NURIMIN,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,1,2,MONTONG ARE,3 TAHUN - 9 BULAN - 1 HARI,2023-02-28,11.2,93.5,1,GIZI KURANG
243,5202804711212960,ZAFIRA NOVIANI,P,2021-11-07,2.6,49,NURHALIMAH,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,0,0,MONTONG ARA,1 TAHUN - 3 BULAN - 21 HARI,2023-02-28,6.9,72.3,1,GIZI KURANG
244,5202083103196754,M. ZIKRI,L,2019-03-31,3.0,49,ISNAINI,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,MONTONG JAYA,1,2,DASAN MONTONG,3 TAHUN - 10 BULAN - 3 HARI,2023-02-02,11.7,94.0,1,GIZI KURANG
245,5202806503180011,ERLIN MARLINA,P,2018-03-25,3.0,48,MUTAHAR,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,TELAGA RENA,3,1,DASAN TELAGE,4 TAHUN - 10 BULAN - 11 HARI,2023-02-04,12.4,99.6,1,GIZI KURANG

In [16]:
data_bulan = data_c['Usia Saat Ukur']
data_bulan

0       0 TAHUN - 8 BULAN - 17 HARI
1       0 TAHUN - 1 BULAN - 19 HARI
2        0 TAHUN - 7 BULAN - 7 HARI
3       0 TAHUN - 5 BULAN - 13 HARI
4       0 TAHUN - 2 BULAN - 12 HARI
                   ...
241     2 TAHUN - 2 BULAN - 20 HARI
242      3 TAHUN - 9 BULAN - 1 HARI
243     1 TAHUN - 3 BULAN - 21 HARI
244     3 TAHUN - 10 BULAN - 3 HARI
245    4 TAHUN - 10 BULAN - 11 HARI
Name: Usia Saat Ukur, Length: 246, dtype: object

In [17]:
def hitungan_bulan(data):
    hasil = []
    for d in data:
        # Pisahkan bagian tahun, bulan, dan hari
        bagian = d.split(" - ")
        tahun = int(bagian[0].split(" TAHUN")[0])
        bulan = int(bagian[1].split(" BULAN")[0])
        hari = int(bagian[2].split(" HARI")[0])

        # Konversi ke hitungan bulan
        total_bulan = tahun * 12 + bulan

        hasil.append(total_bulan)
    
    return hasil

In [18]:
data_c['Usia Saat Ukur'] = hitungan_bulan(data_c['Usia Saat Ukur'])
data_c

,NIK,Nama,JK,Tgl Lahir,BB Lahir,TB Lahir,Nama Ortu,Prov,Kab/Kota,Kec,...,Posyandu,RT,RW,Alamat,Usia Saat Ukur,Tanggal Pengukuran,Berat,Tinggi,Jml Vit A,Label Aktual
0,5202080606192554,KEISYA PUTRI,P,2019-06-06,3.1,50,SRI SEKAR NOVIA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,CINTA DAMAI,1,3,KARANG JANGKONG,8,2020-02-22,9.0,66.0,1,GIZI LEBIH
1,5202084301202131,NUR SYUHADA,P,2020-01-03,3.2,48,NURUL FATIHA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,CINTA DAMAI,1,3,KARANG JANGKONG,1,2020-02-22,5.7,55.0,1,GIZI LEBIH
2,5202081307190004,HAIDAR ALI,L,2019-07-13,2.7,51,KASIRUN,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,7,2020-02-19,8.1,61.0,1,GIZI LEBIH
3,5202084609190008,AMELIA MUTIARA IBRAHIM,P,2019-09-06,2.9,49,IBRAHIM,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,5,2020-02-19,7.3,60.0,1,GIZI LEBIH
4,5202080812190007,M. SAPIK AZRULLAH,L,2019-12-08,3.0,50,MUSTARA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,BERIUK SADAR,1,1,TAPON BARAT,2,2020-02-19,6.3,56.0,1,GIZI LEBIH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,5202080812201000,MUHAMAD GILANG,L,2020-12-08,2.7,48,YANA,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,1,3,MONTONG ARA,26,2023-02-28,7.8,77.0,1,GIZI KURANG
242,5202082905190133,SUKMADANI PRAYASA,L,2019-05-29,3.1,51,NURIMIN,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,1,2,MONTONG ARE,45,2023-02-28,11.2,93.5,1,GIZI KURANG
243,5202804711212960,ZAFIRA NOVIANI,P,2021-11-07,2.6,49,NURHALIMAH,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,HARAPAN JAYA,0,0,MONTONG ARA,15,2023-02-28,6.9,72.3,1,GIZI KURANG
244,5202083103196754,M. ZIKRI,L,2019-03-31,3.0,49,ISNAINI,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,MONTONG JAYA,1,2,DASAN MONTONG,46,2023-02-02,11.7,94.0,1,GIZI KURANG
245,5202806503180011,ERLIN MARLINA,P,2018-03-25,3.0,48,MUTAHAR,NUSA TENGGARA BARAT,LOMBOK TENGAH,PRINGGARATA,...,TELAGA RENA,3,1,DASAN TELAGE,58,2023-02-04,12.4,99.6,1,GIZI KURANG

In [19]:
data_c.to_excel('data final.xlsx', index=False)